# Azure Pipelines documentation https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  displayName: 'Install .NET Core SDK'
  inputs:
    targetType: 'inline'
    script: 'sudo apt-get update && sudo apt-get install -y dotnet-sdk-2.2'
    failOnStderr: true
- task: Bash@3
  displayName: 'Install Cake Tool'
  inputs:
    targetType: 'inline'
    script: 'dotnet tool install --global Cake.Tool'
    failOnStderr: true
- task: Bash@3
  displayName: 'Run Cake'
  inputs:
    targetType: 'inline'
    script: 'dotnet cake'
    failOnStderr: true