# Azure Pipelines documentation https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

variables:
  # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

stages:
- stage: Build
  jobs:
  - job: Build
    strategy:
      matrix:
        Linux:
          matrixName: Ubuntu
          vmImageName: ubuntu-latest
        Mac:
          matrixName: Mac
          vmImageName: macos-latest
        Windows:
          matrixName: Windows
          vmImageName: windows-latest
    pool:
      vmImage: $(vmImageName)
    timeoutInMinutes: 10
    steps:
    - checkout: self
      lfs: true
    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: '3.0.100'
    - script: 'dotnet tool install --global Cake.Tool --version 0.35.0-alpha0037 --add-source https://pkgs.dev.azure.com/cake-build/Cake/_packaging/cake/nuget/v3/index.json'
      displayName: 'Install Cake Tool'
      failOnStderr: true
    - script: 'dotnet cake --target=Build'
      displayName: 'Dotnet Cake Build'
      failOnStderr: true
    - script: 'dotnet cake --target=Test'
      displayName: 'Dotnet Cake Test'
      failOnStderr: true
    - script: 'dotnet cake --target=Pack'
      displayName: 'Dotnet Cake Pack'
      failOnStderr: true
    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '**/*.trx'
    - publish: './build.cake'
      artifact: '$(matrixName)CakeScript'
      displayName: 'Publish Cake Script'
    - publish: './Artefacts'
      artifact: '$(matrixName)Artefacts'
      displayName: 'Publish Artefacts'
- stage: Deploy
  jobs:
  - deployment: AzureArtefacts
    displayName: 'Azure Artefacts'
    pool:
      vmImage: ubuntu-latest
    environment: 'Azure Artefacts'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: UseDotNet@2
            displayName: 'Install .NET Core SDK'
            inputs:
              packageType: 'sdk'
              version: '3.0.100'
          - script: 'dotnet tool install --global Cake.Tool --version 0.35.0-alpha0037 --add-source https://pkgs.dev.azure.com/cake-build/Cake/_packaging/cake/nuget/v3/index.json'
            displayName: 'Install Cake Tool'
            failOnStderr: true
          - task: NuGetAuthenticate@0
          - script: 'dotnet cake $(Agent.BuildDirectory)/WindowsCakeScript/build.cake --target=PushAzureArtefacts --AzureArtefactsOrganization=RehanSaeed'
            displayName: 'Dotnet Cake PushAzureArtefacts'
            failOnStderr: true
  - deployment: GitHub
    pool:
      vmImage: ubuntu-latest
    environment: 'GitHub'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: UseDotNet@2
            displayName: 'Install .NET Core SDK'
            inputs:
              packageType: 'sdk'
              version: '3.0.100'
          - script: 'dotnet tool install --global Cake.Tool --version 0.35.0-alpha0037 --add-source https://pkgs.dev.azure.com/cake-build/Cake/_packaging/cake/nuget/v3/index.json'
            displayName: 'Install Cake Tool'
            failOnStderr: true
          - script: 'dotnet cake $(Agent.BuildDirectory)/WindowsCakeScript/build.cake --target=PushGitHub --GitHubUserName=$(GitHubUserName) --GitHubPassword=$(GitHubPersonalAccessToken)'
            displayName: 'Dotnet Cake PushGitHub'
            failOnStderr: true
  - deployment: NuGet
    pool:
      vmImage: ubuntu-latest
    environment: 'NuGet'
    condition: startsWith(variables['Build.sourceBranch'], 'refs/tags/')
    strategy:
      runOnce:
        deploy:
          steps:
          - task: UseDotNet@2
            displayName: 'Install .NET Core SDK'
            inputs:
              packageType: 'sdk'
              version: '3.0.100'
          - script: 'dotnet tool install --global Cake.Tool --version 0.35.0-alpha0037 --add-source https://pkgs.dev.azure.com/cake-build/Cake/_packaging/cake/nuget/v3/index.json'
            displayName: 'Install Cake Tool'
            failOnStderr: true
          - script: 'dotnet cake $(Agent.BuildDirectory)/WindowsCakeScript/build.cake --target=PushNuGet --NuGetApiKey=$(NuGetApiKey)'
            displayName: 'Dotnet Cake PushNuGet'
            failOnStderr: true
