# Azure Pipelines documentation https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  displayName: 'Install .NET Core SDK'
  inputs:
    targetType: 'inline'
    script: 'apt-get update
      apt-get install dotnet-sdk-2.2=2.2.300'
    failOnStderr: true